# Generated by Django 6.1.1 on 2026-10-01 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_taxi'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='charge_type',
            field=models.IntegerField(choices=[(0, 'distance'), (1, 'time')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxi',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'success')])),
                ('start_point', models.JSONField()),
                ('end_point', models.JSONField()),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='driver_rides', to='base.account')),
                ('passenger_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='passenger_rides', to='base.account')),
            ],
        ),
        migrations.CreateModel(
            name='RideData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_distance_in_kilometers', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_distance_in_kilometers', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_time_in_minutes', models.IntegerField()),
                ('actual_time_in_minutes', models.IntegerField()),
                ('expected_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ride_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ride')),
            ],
        ),
    ]
